use_frameworks!

platform :ios, '9.0'

target 'ORLocation_Example' do
  pod 'ORLocation', :path => '../'

  target 'ORLocation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
